app = "telegram-bot"
primary_region = "cdg"

[build]
  buildpacks = ["paketo-buildpacks/python"]

[env]
  SOURCE_CHANNEL_ID = "-1001779278127"
  DESTINATION_CHANNEL_ID = "-1002264693466"
  SESSION_NAME = "session"
  PORT = "10000"
  PYTHONUNBUFFERED = "1" # Убери, если добавил через `fly secrets set`

[processes]
  app = "python radar.py"  # Или другая команда, которая запускает бота

[mounts]
  source = "bot_data"
  destination = "/data"
